# Generated by Django 5.2.14 on 2026-05-15 01:18

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "provider",
                    models.CharField(
                        choices=[("mock", "Mock"), ("graphhopper", "GraphHopper")],
                        default="mock",
                        max_length=20,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Расстояние, км",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="Время, мин"),
                ),
                (
                    "fuel_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Множитель расхода",
                    ),
                ),
                (
                    "fuel_liters",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Топливо, л",
                    ),
                ),
                (
                    "cost_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Стоимость, руб",
                    ),
                ),
                (
                    "co2_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="CO2, кг",
                    ),
                ),
                (
                    "nox_g",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="NOx, г",
                    ),
                ),
                (
                    "pm_g",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000"))
                        ],
                        verbose_name="PM, г",
                    ),
                ),
                (
                    "eco_rating",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Эко-рейтинг",
                    ),
                ),
                ("geometry_json", models.JSONField(verbose_name="Геометрия маршрута")),
                (
                    "is_selected",
                    models.BooleanField(default=False, verbose_name="Выбран"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "calculation_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_options",
                        to="fleet.ecocalculationsettings",
                        verbose_name="Настройки расчета",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_options",
                        to="orders.shipmentorder",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант маршрута",
                "verbose_name_plural": "Варианты маршрутов",
                "ordering": ("order", "created_at"),
            },
        ),
    ]
