# Generated by Django 5.2.14 on 2026-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routeoption",
            name="route_facts_json",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Факты маршрута"
            ),
        ),
    ]
