# Generated by Django 5.2.14 on 2026-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routing", "0002_routeoption_route_facts_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="routeoption",
            name="calculation_details_json",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Детали расчета"
            ),
        ),
        migrations.AddField(
            model_name="routeoption",
            name="calculation_model_version",
            field=models.CharField(
                default="v1", max_length=20, verbose_name="Версия расчетной модели"
            ),
        ),
    ]
