# Generated by Django 5.2.14 on 2026-05-15 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("routing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("in_progress", "В пути"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "planned_start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Плановое начало"
                    ),
                ),
                (
                    "actual_start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактическое начало"
                    ),
                ),
                (
                    "actual_finish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактическое завершение"
                    ),
                ),
                (
                    "waybill_pdf",
                    models.FileField(
                        blank=True,
                        upload_to="waybills/",
                        verbose_name="PDF-путевой лист",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip",
                        to="orders.shipmentorder",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "route_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="routing.routeoption",
                        verbose_name="Выбранный маршрут",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейс",
                "verbose_name_plural": "Рейсы",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TripStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planned", "Запланирован"),
                            ("in_progress", "В пути"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                        ],
                        max_length=20,
                        verbose_name="Предыдущий статус",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("in_progress", "В пути"),
                            ("delivered", "Доставлен"),
                            ("cancelled", "Отменен"),
                        ],
                        max_length=20,
                        verbose_name="Новый статус",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время изменения"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_status_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Изменил",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="trips.trip",
                        verbose_name="Рейс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие статуса рейса",
                "verbose_name_plural": "События статусов рейсов",
                "ordering": ("changed_at",),
            },
        ),
    ]
