# Generated by Django 5.2.14 on 2026-05-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripstatusevent",
            name="event_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Фактическое время события"
            ),
        ),
    ]
