# Generated by Django 5.2.14 on 2026-06-07 01:01

from django.db import migrations, models

import apps.accounts.models
import apps.accounts.storage


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                storage=apps.accounts.storage.ProfileAvatarStorage(),
                upload_to=apps.accounts.models.profile_avatar_upload_to,
                verbose_name="Фото профиля",
            ),
        ),
    ]
