# Generated by Django 5.2.14 on 2026-05-22 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.reports.models
import apps.reports.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("trips", "0002_tripstatusevent_event_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("waybill_pdf", "Путевой лист PDF"),
                            ("emissions_pdf", "Отчет по выбросам PDF"),
                            ("emissions_xlsx", "Отчет по выбросам Excel"),
                            ("admin_analytics_xlsx", "Сводка компании Excel"),
                            ("trips_xlsx", "Экспорт рейсов Excel"),
                        ],
                        max_length=32,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xlsx", "XLSX")],
                        max_length=8,
                        verbose_name="Формат файла",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "file",
                    models.FileField(
                        storage=apps.reports.storage.DocumentArchiveStorage(),
                        upload_to=apps.reports.models.archived_document_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True, verbose_name="Дата с")),
                ("date_to", models.DateField(blank=True, null=True, verbose_name="Дата по")),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(default=0, verbose_name="Размер файла, байт"),
                ),
                (
                    "metadata_json",
                    models.JSONField(blank=True, default=dict, verbose_name="Метаданные"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_archived_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_documents",
                        to="orders.shipmentorder",
                        verbose_name="Связанная заявка",
                    ),
                ),
                (
                    "related_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_documents",
                        to="trips.trip",
                        verbose_name="Связанный рейс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Архивный документ",
                "verbose_name_plural": "Архивные документы",
                "ordering": ("-created_at",),
            },
        ),
    ]
