# Generated by Django 5.2.14 on 2026-05-19 11:56

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecocalculationsettings",
            name="driver_time_tariff_rub_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("900.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Тариф времени водителя, руб/ч",
            ),
        ),
    ]
