from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from .views import (
    AnalyticsSummaryAPIView,
    ApproveRouteAPIView,
    ArchiveDeleteAPIView,
    ArchiveDownloadAPIView,
    ArchiveListAPIView,
    CurrentUserAPIView,
    EmissionsReportAPIView,
    EmissionsReportPdfAPIView,
    EmissionsReportPdfArchiveAPIView,
    EmissionsReportXlsxAPIView,
    EmissionsReportXlsxArchiveAPIView,
    LocationListAPIView,
    ManagerDashboardAPIView,
    OrderCalculateRoutesAPIView,
    OrderCancelAPIView,
    OrderDetailAPIView,
    OrderListAPIView,
    OrderRouteCalculationStatusAPIView,
    OrderRouteOptionsAPIView,
    ProfileAPIView,
    ProfileAvatarAPIView,
    TransportListAPIView,
    TripDeliverAPIView,
    TripDetailAPIView,
    TripExportXlsxAPIView,
    TripExportXlsxArchiveAPIView,
    TripListAPIView,
    TripStartAPIView,
    TripWaybillAPIView,
    TripWaybillArchiveAPIView,
)

app_name = "api"

urlpatterns = [
    path("auth/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("auth/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("auth/me/", CurrentUserAPIView.as_view(), name="auth_me"),
    path("profile/", ProfileAPIView.as_view(), name="profile"),
    path("profile/avatar/", ProfileAvatarAPIView.as_view(), name="profile_avatar"),
    path("manager/dashboard/", ManagerDashboardAPIView.as_view(), name="manager_dashboard"),
    path("locations/", LocationListAPIView.as_view(), name="locations"),
    path("transports/", TransportListAPIView.as_view(), name="transports"),
    path("orders/", OrderListAPIView.as_view(), name="orders"),
    path("orders/<int:pk>/", OrderDetailAPIView.as_view(), name="order_detail"),
    path("orders/<int:pk>/cancel/", OrderCancelAPIView.as_view(), name="order_cancel"),
    path(
        "orders/<int:pk>/calculate-routes/",
        OrderCalculateRoutesAPIView.as_view(),
        name="order_calculate_routes",
    ),
    path(
        "orders/<int:pk>/route-calculation-status/",
        OrderRouteCalculationStatusAPIView.as_view(),
        name="order_route_calculation_status",
    ),
    path(
        "orders/<int:pk>/route-options/",
        OrderRouteOptionsAPIView.as_view(),
        name="order_route_options",
    ),
    path(
        "orders/<int:order_pk>/routes/<int:route_option_pk>/approve/",
        ApproveRouteAPIView.as_view(),
        name="approve_route",
    ),
    path("trips/", TripListAPIView.as_view(), name="trips"),
    path("trips/export-xlsx/", TripExportXlsxAPIView.as_view(), name="trips_export_xlsx"),
    path(
        "trips/export-xlsx/archive/",
        TripExportXlsxArchiveAPIView.as_view(),
        name="trips_export_xlsx_archive",
    ),
    path("trips/<int:pk>/", TripDetailAPIView.as_view(), name="trip_detail"),
    path("trips/<int:pk>/start/", TripStartAPIView.as_view(), name="trip_start"),
    path("trips/<int:pk>/deliver/", TripDeliverAPIView.as_view(), name="trip_deliver"),
    path("trips/<int:pk>/waybill/", TripWaybillAPIView.as_view(), name="trip_waybill"),
    path(
        "trips/<int:pk>/waybill/archive/",
        TripWaybillArchiveAPIView.as_view(),
        name="trip_waybill_archive",
    ),
    path("reports/emissions/", EmissionsReportAPIView.as_view(), name="emissions_report"),
    path(
        "reports/emissions/pdf/",
        EmissionsReportPdfAPIView.as_view(),
        name="emissions_report_pdf",
    ),
    path(
        "reports/emissions/pdf/archive/",
        EmissionsReportPdfArchiveAPIView.as_view(),
        name="emissions_report_pdf_archive",
    ),
    path(
        "reports/emissions/xlsx/",
        EmissionsReportXlsxAPIView.as_view(),
        name="emissions_report_xlsx",
    ),
    path(
        "reports/emissions/xlsx/archive/",
        EmissionsReportXlsxArchiveAPIView.as_view(),
        name="emissions_report_xlsx_archive",
    ),
    path("reports/archive/", ArchiveListAPIView.as_view(), name="archive"),
    path(
        "reports/archive/<int:pk>/download/",
        ArchiveDownloadAPIView.as_view(),
        name="archive_download",
    ),
    path("reports/archive/<int:pk>/", ArchiveDeleteAPIView.as_view(), name="archive_delete"),
    path("analytics/summary/", AnalyticsSummaryAPIView.as_view(), name="analytics_summary"),
]
